import { Router } from '@vaadin/router';

import './theme/base.css';
import './api/api-status.js';
import './components/ml-loading.js';
import './components/ml-message.js';
import './components/ml-badge.js';
import './components/ml-avatar.js';
import './components/ml-card.js';
import './components/ml-button.js';
import './components/ml-pagination.js';
import './components/notifications-dropdown.js';
import './app/app-shell.js';
import './icons/icon.js';
import './views/home-view.js';
import './views/group-view.js';
import './views/thread-view.js';
import './views/login-view.js';
import './views/register-view.js';
import './views/profile-view.js';
import './views/install-view.js';
import './views/admin-view.js';
import './views/pms-view.js';
import './views/about-view.js';
import './views/not-found-view.js';